# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('members', models.IntegerField(default=1, null=True)),
                ('light_needs', models.IntegerField(default=0)),
                ('sound_needs', models.IntegerField(default=0)),
                ('specific_needs', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Concert', max_length=50)),
                ('date', models.DateField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivalapp.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_status', models.CharField(choices=[('arranger', 'ARRANGER'), ('sound_technician', 'LYDTEKNIKER'), ('light_technician', 'LYSTEKNIKER'), ('manager', 'MANAGER')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Scene', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='lightingWork',
            field=models.ManyToManyField(related_name='lighting', to='festivalapp.Employee'),
        ),
        migrations.AddField(
            model_name='concert',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivalapp.Scene'),
        ),
        migrations.AddField(
            model_name='concert',
            name='soundWork',
            field=models.ManyToManyField(related_name='sound', to='festivalapp.Employee'),
        ),
        migrations.AddField(
            model_name='band',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='festivalapp.Employee'),
        ),
    ]
