# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='lightingWork',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='soundWork',
        ),
        migrations.AddField(
            model_name='band',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concert',
            name='audience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.CharField(choices=[('rock', 'ROCK'), ('pop', 'POP'), ('electric', 'ELECTRIC')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='lighting_work',
            field=models.ManyToManyField(blank=True, related_name='lighting', to='festivalapp.Employee'),
        ),
        migrations.AddField(
            model_name='concert',
            name='sound_work',
            field=models.ManyToManyField(blank=True, related_name='sound', to='festivalapp.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('arranger', 'ARRANGER'), ('sound_technician', 'LYDTEKNIKER'), ('light_technician', 'LYSTEKNIKER'), ('manager', 'MANAGER'), ('booking_responsible', 'BOOKINGANSVARLIG')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='concert',
            name='festival',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='festivalapp.Festival'),
        ),
    ]
