# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertrequest',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='concertrequest',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='genre',
            field=models.CharField(choices=[('Rock', 'ROCK'), ('Pop', 'POP'), ('Electric', 'ELECTRIC')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='concertrequest',
            name='genre',
            field=models.CharField(choices=[('Rock', 'ROCK'), ('Pop', 'POP'), ('Electric', 'ELECTRIC')], default=None, max_length=32, null=True),
        ),
    ]
