# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
