# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band', to='festivalapp.Band'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='festival',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='festival', to='festivalapp.Festival'),
        ),
    ]
