# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='review',
            field=models.TextField(default='No review yet'),
        ),
    ]
