# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0002_concert_ticket_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='review',
            field=models.TextField(default='No review yet'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='genre',
            field=models.CharField(choices=[('rock', 'ROCK'), ('pop', 'POP'), ('electric', 'ELECTRIC')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(default='Concert', max_length=50),
        ),
        migrations.AlterField(
            model_name='concertrequest',
            name='genre',
            field=models.CharField(choices=[('rock', 'ROCK'), ('pop', 'POP'), ('electric', 'ELECTRIC')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='concertrequest',
            name='name',
            field=models.CharField(default='Concert', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('arranger', 'ARRANGER'), ('sound_technician', 'LYDTEKNIKER'), ('light_technician', 'LYSTEKNIKER'), ('manager', 'MANAGER'), ('booking_responsible', 'BOOKINGANSVARLIG'), ('booking_boss', 'BOOKINGSJEF'), ('pr_manager', 'PR-MANAGER'), ('service_manager', 'SERVICE MANAGER'), ('band_member', 'BAND MEMBER')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(default='Scene', max_length=50),
        ),
    ]
