# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0002_auto_20170918_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('arrangør', 'ARRANGØR'), ('lydtekniker', 'LYDTEKNIKER'), ('lystekniker', 'LYSTEKNIKER')], max_length=32),
        ),
    ]
