# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0003_auto_20171030_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertrequest',
            name='is_sendt',
            field=models.BooleanField(default=False),
        ),
    ]
