# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0003_auto_20171002_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
