# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0004_auto_20170920_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='band',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='scene',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('arranger', 'ARRANGØR'), ('sound_technician', 'LYDTEKNIKER'), ('light_technician', 'LYSTEKNIKER')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
    ]
