# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0004_concertrequest_is_sendt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='specific_needs',
            field=models.TextField(default='No specific needs yet'),
        ),
    ]
