# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0004_auto_20170920_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='bands',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='scenes',
            new_name='scene',
        ),
        migrations.AddField(
            model_name='concert',
            name='lightingWork',
            field=models.ManyToManyField(related_name='lighting', to='festivalapp.Employee'),
        ),
        migrations.AddField(
            model_name='concert',
            name='soundWork',
            field=models.ManyToManyField(related_name='sound', to='festivalapp.Employee'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(default='Concert', max_length=50),
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(default='bandName', max_length=50),
        ),
    ]
