# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0005_auto_20170921_1523'),
        ('festivalapp', '0005_auto_20170921_1144'),
    ]

    operations = [
    ]
